### PR TITLE
Added customStyles to Popover

### PR DESCRIPTION
**Pull request by h2000**
Added new Function customStyles:
Add custom style attributes to popover, for example to change the width of the popover:
...
|> Popover.titleH4 [] [ text "My title" ]
|> Popover.customStyles [("width","600px"), ("max-width","600px")]
...

### CODE REVIEW

**Comment by h2000** [comment]
Hello Magnus, is there any problem with the pull request?

**Comment by rundis** [comment]
Sorry for not getting back to you. Things have been a bit crazy with organizing Oslo Elm Day (conference) and redoing our kitchen at home. I hope to get some time to look at it soonish.

**Comment by h2000** [comment]
No Problem! 
Btw. thx a lot for ur great work!

**Comment by h2000** [comment]
Hello Magnus, how is the current status of this change request.

Btw. thx for the cool videos from Oslo-Elm-Day.

**Comment by rundis** [comment]
Cheers !

Didn't have time to attend to any opensource stuff before I went on holiday. Back in business in August. Sorry for the delay.

**Comment by rundis** [comment]
Finally got some time to look at this. 
My initial feeling is that this is a bit of a foot gun. If you start messing with width/dimensions the positioning logic quickly goes down the drain. 

If you want to customize the bootstrap look in general (besides stuff that has to do with sizing and positioning), maybe it would be better to do that with custom css overrides or using compiling your own custom bootstrap css using sass or whatever.

**Pull request closed without merging**
