### PR TITLE
Add Progress.progressWithAttrs

### PR DESCRIPTION
**Pull request by anacrolix**
Needed an onClick handler on the parent div.

### CODE REVIEW

**Comment by rundis** [comment]
Sorry for the slow response.

I think the APi would be better if we introduced a wrapperAttrs function which creates a 
`WrapperAttrs (List (Html.Attributes msg))`  Option.

**Comment by anacrolix** [comment]
Do you mean `wrapperAttrs : List (Html.Attributes msg) -> Option msg`?

**Comment by rundis** [comment]
Well both. You need an additional  type constructor and a user facing api function that uses the new type constructor.

**Comment by rundis** [comment]
I added support for this in version 3.0.0. Let me know if that works out for you. If not please raise a new issue. Cheers !

**Comment by anacrolix** [comment]
Thank you

**Pull request closed without merging**
