### PR TITLE
Added "accordion" class to Accordion parent div

### PR DESCRIPTION
**Pull request by andrewjackman**
…correctly show the cards as one item with rounding of corners of top/bottom of first/last cards only.

See Issue #129

### CODE REVIEW

**Comment by rundis** [comment]
Sorry, but could you rebase this to resolve any conflicts and I'll include it in the next release. (Sorry for not including this in the upgrade, got lost in all the things to keep track of.). Cheers.

**Comment by andrewjackman** [comment]
Apologies for the long delay - been busy with new baby and changing job :D

I have merged this change. I forgot to bump the version, so will do that and then publish...

**Comment by andrewjackman** [comment]
Ah oops - I replied to wrong email. Will rebase now...

**Comment by andrewjackman** [comment]
OK rebased.

**Comment by rundis** [comment]
Fixed with commit #dfbad63

**Pull request closed without merging**
