### PR TITLE
Allows for Msgs to use tab.id during tab onClick

### PR DESCRIPTION
**Pull request by JasonMFry**
This makes it possible to return a more robust Msg (for instance, one
that triggers an API call) for each tab click.

This supersedes https://github.com/rundis/elm-bootstrap/pull/122.

### CODE REVIEW

**Comment by rundis** [comment]
I see what you are getting at. Problem with this approach is that when using animations you will get multiple messages for the same id.

**Comment by rundis** [comment]
Workaround for now is If you **don't** override the click handler for links and set useHash to True, I'm pretty sure you can achieve your end-goal... but you do have to route match on the hash of course. I'll see if I have time to knock up a small Ellie if you're unsure on how to do it.

**Comment by JasonMFry** [comment]
We're not using animations so we weren't aware of that, that's a good point.

To your suggestion to route match on the hash, we have up to 33 tabs (matching 33 rows in a database table) which would significantly bloat code on frontend and backend. Plus we could add more rows to our table which would necessitate a change to the frontend and backend, whereas what we have now would not.

**Comment by rundis** [comment]
I'm not sure I buy the significant bloat statement 🤔 I don't see how matching on routes would incur much more code, it's just a different way of getting hold of the selected tab id. Here's a quick simplified ellie for matching on route hash: https://ellie-app.com/ZVN3PY2YJma1

I can see that if the app doesn't use navigation in the first place, then It's obviously some overhead introducing navigation and url parser.

I think in order to support "event like" feedback an update function (returning a tuple of state and "event") is probably  needed. That would obviously make the tabs api less nice for simpler cases. I'm open to api design suggestions which explains how that has a nicer balance between simple and more complex use cases 😄 

I'm not going to accept this PR as it stands though.

**Comment by rundis** [comment]
Also, people have previously asked for the hash feature, because they support deep linking into their App so it's sort of providing a dual benefit (deep linking and facility to act upon hash change with side effects)

**Comment by JasonMFry** [comment]
Thanks for the Ellie! You're right, I think this will work.

**Pull request closed without merging**
