### PR TITLE
Tests

### PR DESCRIPTION
**Pull request by dseebacher**
I started to add some tests based on the _elm-coverage_ output. Some might not be the most important ones, but its a way to get into it.
And i pushed elm-format to 0.7, this might mess the diffs up a little on a pr level.

### CODE REVIEW

**Comment by rundis** [comment]
Great ! But could you remove the commit for formatting. I've started porting to 0.19 and it would be causing me unnecessary merge efforts. I'll be updating elm-format and include in CI build eventually... just have some patience 😄

**Comment by dseebacher** [comment]
what version of elm-format do you use?

**Comment by rundis** [comment]
0.6.1-alpha

**Comment by dseebacher** [comment]
Ok, done!

**Comment by rundis** [comment]
tx, great stuff !

**Pull request merged**
